#
# Makefile for the kernel TCC T3170 CORE
#

obj-y += CORE.o

  CORE-y += TC317X_Core.o
  CORE-y += TC317X_Core_GPIO.o
  CORE-y += TC317X_Core_I2CMS.o
  CORE-y += TC317X_Core_Interrupt.o
  CORE-y += TC317X_Core_Mailbox.o
  CORE-y += TC317X_Core_Peri.o
  CORE-y += TC317X_Core_RegCtrl.o
  CORE-y += TC317X_Core_RFCtrl.o
  CORE-y += TC317X_Core_TDMB.o
  CORE-y += TC317X_Core_Util.o
  CORE-y += TC317X_device_Interrupt_Task.o
  CORE-y += TC317X_deviceAPI.o
  CORE-y += TCC3170RF.o
