--- drivers/gpu/msm/Makefile
+++ drivers/gpu/msm/Makefile
@@ -1,37 +1,23 @@
 ccflags-y := -Iinclude/drm
 
-msm_kgsl_core-y = \
+msm_kgsl-y = \
+	kgsl_drawctxt.o \
+	kgsl_cmdstream.o \
 	kgsl.o \
+	kgsl_log.o \
+	kgsl_mmu.o \
+	kgsl_postmortem.o \
+	kgsl_ringbuffer.o \
 	kgsl_sharedmem.o \
+	kgsl_yamato.o \
+	kgsl_g12_drawctxt.o \
+	kgsl_g12_cmdstream.o \
 	kgsl_pwrctrl.o \
-	kgsl_pwrscale.o \
-	kgsl_mmu.o \
-	kgsl_gpummu.o
-
-msm_kgsl_core-$(CONFIG_DEBUG_FS) += kgsl_debugfs.o
-msm_kgsl_core-$(CONFIG_MSM_KGSL_CFF_DUMP) += kgsl_cffdump.o
-msm_kgsl_core-$(CONFIG_MSM_KGSL_DRM) += kgsl_drm.o
-msm_kgsl_core-$(CONFIG_MSM_SCM) += kgsl_pwrscale_trustzone.o
-msm_kgsl_core-$(CONFIG_MSM_SLEEP_STATS) += kgsl_pwrscale_idlestats.o
-
-msm_adreno-y += \
-	adreno_ringbuffer.o \
-	adreno_drawctxt.o \
-	adreno_postmortem.o \
-	adreno_a2xx.o \
-	adreno.o
-
-msm_adreno-$(CONFIG_DEBUG_FS) += adreno_debugfs.o
-
-msm_z180-y += z180.o
+	kgsl_g12.o
 
-msm_kgsl_core-objs = $(msm_kgsl_core-y)
-msm_adreno-objs = $(msm_adreno-y)
-msm_z180-objs = $(msm_z180-y)
+msm_kgsl-$(CONFIG_MSM_KGSL_CFF_DUMP) += kgsl_cffdump.o
+msm_kgsl-$(CONFIG_MSM_KGSL_DRM) += kgsl_drm.o
 
-obj-$(CONFIG_MSM_KGSL) += msm_kgsl_core.o
-obj-$(CONFIG_MSM_KGSL) += msm_adreno.o
-obj-$(CONFIG_MSM_KGSL_2D) += msm_z180.o
+msm_kgsl-objs = $(msm_kgsl-y)
 
-# Ignore warnings to prevent build breaks when using gcc 4.5.0
-CFLAGS_REMOVE_kgsl_log.o = -Werror
+obj-$(CONFIG_MSM_KGSL) += msm_kgsl.o
