
# Kernel makefile for motions sensors
#
# 

obj-$(CONFIG_EF39S_SENSORS_APDS9900_HW) += apds9900.o proximity.o ambientlight.o
obj-$(CONFIG_EF39S_SENSORS_APDS9900_SW) += apds9900.o proximity.o ambientlight.o

